# =============================================
# springboot 2 configurations
# ---------------------------------------------
spring:
  application:
    name: ${OPENSHIFT_APP_NAME:openbanking-proxy-policy}
  datasource:
    initialization-mode: never

api:
  title: ${OPENSHIFT_APP_NAME:openbanking-proxy-policy}
  description: 3scale-proxy-policy
  version: 1
  hostname: ${OPENSHIFT_HOST_NAME:openbanking-proxy-policy.apps.openshift.com}

logging:
  config: classpath:logback.xml
  level:
    root: INFO

# options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
camel:
  health:
    check:
      routes:
        enabled: true
      indicator:
        enabled: true
      service:
        enabled: true
  springboot:
    name: ${OPENSHIFT_APP_NAME:openbanking-proxy-policy}
    main-run-controller: true
  component:
    jmxEnabled: true

# lets listen on all ports to ensure we can be invoked from the pod ip address
server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8090}

# lets use a different management port in case you need to listen to HTTP requests on 8080
management:
  security:
    enabled: false
  server:
    # default health-check probe port: 8081
    port: 8081
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - jvm
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true

# =============================================
# opentracing configurations
# see: https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/README.md
# ---------------------------------------------
opentracing:
  jaeger:
    enabled: true
    service-name: ${OPENSHIFT_APP_NAME:openbanking-proxy-policy}
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      #url: http://jaeger-collector:14268/api/traces
      url: ${OPENSHIFT_JAEGER_TRACE_API_URL:http://localhost:14268/api/traces}
      # password:
      # username:
    expand-exception-logs: true
    remote-reporter:
      max-queue-size: 10000
      flush-interval: 1000
    tags:
      - openbanking
      - proxy
      - ip-rate-limit
    include-jaeger-env-tags: false

# =============================================
# custom configurations
# ---------------------------------------------
custom:
  policy:
    ipratelimit:
      maxhitcount: ${MAX_IP_HIT_COUNT:10}
      # milliseconds time window for external requests
      timeWindow: ${TIME_WINDOW:30000}
  dev:
    env: ${DEV_ENV:true}
  endpoint:
  rhdg:
    cache:
      name: ${CACHE_NAME:default}
    health:
      check:
        host: ${JDG_APP_NAME:datagrid-fuse-policy}.${JDG_SERVICE_NAMESPACE:rh-datagrid-73}.svc:9990

# =============================================
# datagrid configurations
# Native Keys of API. With this keys is possible to send the properties file as parameter in ConfigurationBuilder.
# see (configurationBuilder.withProperties(file properties);)
# ---------------------------------------------
infinispan:
  client:
    hotrod:
      #auth_server_name:
      #auth_username:
      #auth_password:
      #use_auth: false
      connect_timeout: ${RHDG_HOTROD_CONN_TIMEOUT:5000}
      socket_timeout: ${RHDG_HOTROD_SOCKET_TIMEOUT:5000}
      max_retries: 5
      server_list: ${JDG_APP_NAME:datagrid-fuse-policy}.${JDG_SERVICE_NAMESPACE:rh-datagrid-73}.svc:11222
  hotrod:
    trustStoreFileName: ${SERVICE_CA:/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt}
    host: ${JDG_APP_NAME:datagrid-fuse-policy}.${JDG_SERVICE_NAMESPACE:rh-datagrid-73}.svc
    port: ${JDG_HOTROD_PORT:11222}
    username:
    password:
