# =============================================
# springboot 2 configurations
# ---------------------------------------------
spring:
  application:
    name: ${OPENSHIFT_APP_NAME:3scale-proxy-policy}
  datasource:
    initialization-mode: never

api:
  title: ${OPENSHIFT_APP_NAME:3scale-proxy-policy}
  description: 3scale-proxy-policy
  version: 1
  hostname: ${OPENSHIFT_HOST_NAME:apps.openshift.raphael.lab.upshift.rdu2.redhat.com}

logging:
  config: classpath:logback.xml
  level:
    root: INFO

camel:
  health:
    check:
      routes:
        enabled: true
      indicator:
        enabled: true
      service:
        enabled: true
  springboot:
    name: ${OPENSHIFT_APP_NAME:3scale-proxy-policy}
    main-run-controller: true
  component:
    jmxEnabled: true

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8090}

management:
  security:
    enabled: false
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - jvm
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true

# =============================================
# opentracing configurations
# ---------------------------------------------
# see:
# https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/README.md
# https://medium.com/jaegertracing/help-something-is-wrong-with-my-jaeger-installation-68874395a7a6
# https://medium.com/@krushnatkhawale/opentracing-using-jaeger-with-spring-boot-web-application-ceaf8dd99fe9
# https://camel.apache.org/components/latest/others/opentracing.html
# https://github.com/jaegertracing/jaeger-client-java/issues/607
# https://grafana.com/blog/2020/07/09/where-did-all-my-spans-go-a-guide-to-diagnosing-dropped-spans-in-jaeger-distributed-tracing/
# https://opentracing.io/guides/java/
# ---------------------------------------------

opentracing:
  jaeger:
    enabled: true
    service-name: ${OPENSHIFT_APP_NAME:3scale-proxy-policy}
    enable-b3-propagation: ${OPENSHIFT_JAEGER_B3_PROPAGATION:false}
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: ${OPENSHIFT_JAEGER_HTTP_SENDER_URI:http://localhost:14268/api/traces}
    expand-exception-logs: true
    probabilistic-sampler:
      sampling-rate: 1
    remote-reporter:
      max-queue-size: ${OPENSHIFT_JAEGER_REPORTER_QUEUE_SIZE:5}
      flush-interval: ${OPENSHIFT_JAEGER_REPORTER_FLUSH_INTERVAL:5}
    tags:
      - 3scale
      - proxy
      - ip-rate-limit

# =============================================
# datagrid configurations
# ---------------------------------------------
infinispan:
  health:
    host: ${INFINISPAN_APP_NAME:datagrid-fuse-policy}.${INFINISPAN_SERVICE_NAMESPACE:rh-datagrid-73}.svc:9990
  client:
    hotrod:
      username: ${INFINISPAN_HOTROD_USERNAME:}
      password: ${INFINISPAN_HOTROD_PASSWORD:}
      use-authn: ${INFINISPAN_HOTROD_AUTHN_ENABLED:false}
      connection-timeout: ${INFINISPAN_HOTROD_CONNECTION_TIMEOUT:3000}
      socket-timeout: ${INFINISPAN_HOTROD_SOCKET_TIMEOUT:3000}
      max-retries: ${INFINISPAN_HOTROD_MAX_RETRIES:2}
      trust-store-path: ${SERVICE_CA_PATH:/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt}
      #host: ${INFINISPAN_APP_NAME:datagrid-fuse-policy}.${INFINISPAN_SERVICE_NAMESPACE:rh-datagrid-73}.svc
      host: ${INFINISPAN_HOTROD_HOST:localhost}
      port: ${INFINISPAN_HOTROD_PORT:11222}
      cache: ${INFINISPAN_CACHE:default}

# =============================================
# custom configurations
# ---------------------------------------------
custom:
  proxy:
    consumer: ${FUSE_PROXY_CONSUMER_COMPONENT:netty4-http}
    producer: ${FUSE_PROXY_PRODUCER_COMPONENT:http4}
    https-port: ${FUSE_PROXY_HTTP_PORT:8443}
    http-port: ${FUSE_PROXY_HTTPS_PORT:8080}
    producer-query: ${FUSE_PRODUCER_QUERY:?connectionClose=false&bridgeEndpoint=true&copyHeaders=true}
    keystore:
      #dest: ${FUSE_PROXY_KEYSTORE_DESTINATION:/deployments/data/keystore.jks}
      #pass: ${FUSE_PROXY_KEYSTORE_PASSWORD:49CNOIPBvFh6b9yKpzK9PKCr1}
      dest: ${FUSE_PROXY_KEYSTORE_DESTINATION:}
      pass: ${FUSE_PROXY_KEYSTORE_PASSWORD:}
    debug: ${FUSE_PROXY_DEBUG:true}
  policy:
    ip-rate-limit:
      max-hit-count: ${POLICY_IP_RATE_LIMIT_MAX_HIT_COUNT:10}
      # milliseconds time window for external requests
      # 1 minute = 60s = 60000ms
      time-window: ${POLICY_IP_RATE_LIMIT_TIME_WINDOW:60000}
      x-forwarded-for: ${POLICY_IP_RATE_LIMIT_X_FORWARDED_FOR:10.6.128.23,200.164.107.55}
      white-list-ips: ${POLICY_IP_RATE_LIMIT_WHITE_LIST_IPS:}
      debug: ${FUSE_POLICY_DEBUG:true}
