# =============================================
# springboot 2 configurations
# ---------------------------------------------
spring:
  application:
    name: proxy #${OPENSHIFT_APP_NAME:openbanking-admin-api}
  datasource:    
    initialization-mode: never

logging:
  config: classpath:logback.xml
  level:
    root: INFO

# options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
camel:
  springboot:
    name: proxy # ${OPENSHIFT_APP_NAME:openbanking-admin-api}


# lets listen on all ports to ensure we can be invoked from the pod ip address
server:
  address: 0.0.0.0
  port: 8085


endpoints:
  enabled: false
  health:
    enabled: true
  actuator:
    enabled: true
  camelhealthcheck:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true
  jmx:
    enabled: true


# lets use a different management port in case you need to listen to HTTP requests on 8080
management:
  port: 8090   
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - jvm
          - prometheus
    metrics:
      export:
        prometheus:
          enabled: true



custom:
  policy: 
    ipratelimit:
      maxhitcount: 40
      # Milliseconds time windows for requests
      timeWindow: 30000
  dev:
    env: false
  endpoint:
  rhdg:
    cache:
      name: cache-ip-rate-limit
    health:
      check:
        host: 127.0.0.1:9990


# =============================================
# opentracing configurations
# see: 
# ---------------------------------------------


# Native Keys of API. With this keys is possible to send the properties file as parameter in ConfigurationBuilder. See (configurationBuilder.withProperties(file properties);)
infinispan:
  client:
    hotrod:
      auth_server_name:
      auth_username:
      auth_password:
      use_auth: false
      connect_timeout: 5000
      socket_timeout: 5000
      max_retries: 3
      server_list: 127.0.0.1:11222
  hotrod:
    host: 127.0.0.1
    port: 11222