# =============================================
# springboot 2 configurations
# ---------------------------------------------
spring:
  application:
    name: ${OPENSHIFT_APP_NAME:openbanking-proxy-policy}
  datasource:    
    initialization-mode: never

debug: true

logging:
  config: classpath:logback.xml
  level:
    root: INFO

# options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
camel:
  springboot:
    name: ${OPENSHIFT_APP_NAME:openbanking-proxy-policy}


# lets listen on all ports to ensure we can be invoked from the pod ip address
server:
  address: 0.0.0.0
  port: 8081


endpoints:
  enabled: false
  health:
    enabled: true
  actuator:
    enabled: true
  camelhealthcheck:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true
  jmx:
    enabled: true


# lets use a different management port in case you need to listen to HTTP requests on 8080
management:
  port: 8090   
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - jvm
          - prometheus
    metrics:
      export:
        prometheus:
          enabled: true



custom:
  policy: 
    ipratelimit:
      maxhitcount: ${MAX_IP_HIT_COUNT:100}
      # Milliseconds time windows for requests
      timeWindow: ${TIME_WINDOW:60000}
  dev:
    env: false
  endpoint:
  rhdg:
    cache:
      name: ${CACHE_NAME:default}
    health:
      check:
        host: ${JDG_APP_NAME}.${JDG_SERVICE_NAMESPACE}.svc:9990


# =============================================
# opentracing configurations
# see: 
# ---------------------------------------------


# Native Keys of API. With this keys is possible to send the properties file as parameter in ConfigurationBuilder. See (configurationBuilder.withProperties(file properties);)
infinispan:
  client:
    hotrod:
      auth_server_name:
      auth_username: 
      auth_password: 
      use_auth: false
      connect_timeout: 5000
      socket_timeout: 5000
      max_retries: 3
      server_list: ${JDG_APP_NAME}.${JDG_SERVICE_NAMESPACE}.svc:11222
  hotrod:
    trustStoreFileName: ${SERVICE_CA:/}
    host: ${JDG_APP_NAME}.${JDG_SERVICE_NAMESPACE}.svc
    port: 11222
    username: 
    password: 